### ISSUE TITLE
csproj file missing

### ISSUE THREAD

**Issue by IDEDOnline** [Masonc2011/Tutorial_GameState#1]
This project is missing the core project file, thus cannot be used by anyone without manually building your own project to load in the files

**Comment by Masonc2011** [comment]
If you're using Visual Studio, which is what this was built with, you open the .sln file.

**Comment by IDEDOnline** [comment]
That's exactly what I did and IDE reported that the csproj was missing and thus the project (part of any solution) cannot be loaded.
I just created the project file myself and reimported all the relevant files to make it work.
